# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f3c858093b303488f3b6e9470517fa35ee13ac5c5aeb29648fb96bd445ea1f23551652fa76381eeb077801039912d8590c780919afd8825af6889847b567bc

test:
  secret_key_base: 280ba771c7c2035631cbcd734220713542cf79b6d54784f12940dadb0aa2a696c0def3c33037922e8ddda25c3190d625af0ea178656863b323c569aa8859be89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
